import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

// initialize font
const poppins = Poppins(
  {
    weight: ['100', '200', '400', '500', '600', '800'],
  }
);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // use the font to entire html body
        className={`${poppins.className} antialiased`}
      >
        <header>
          <Navbar />
        </header>

        <main>
          {children}
        </main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
