import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import localFont from 'next/font/local'

// initialize font
const poppins = Poppins(
  {
    weight: ['100', '200', '400', '500', '600', '800'],
  }
);

// meta data for SEO
export const metadata = {
  title: "Hero Kidz",
  description: "Generated by create next app",
};

// local font 
export const fontBangla = localFont({
  src: './../fonts/mayaboti-normal.ttf',
  // weight: ""
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // use the font to entire html body
        className={`${poppins.className} antialiased`}
      >
        <header>
          <Navbar />
        </header>

        <main className="py-2 md:w-7xl mx-auto min-h-[calc(100vh-287px)]">
          {children}
        </main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
